name: local_auth_showcase
description: "An example of local user authentication on a device."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: 14.8.1
  google_fonts: 6.2.1

dev_dependencies:
  build_runner: 2.4.15
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: 2.8.2

flutter:
  uses-material-design: true
