name: local_auth_showcase
description: "An example of local user authentication on a device."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  bloc: 9.0.0
  crypto: 3.0.6
  equatable: 2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.0
  freezed_annotation: 3.0.0
  go_router: 14.8.1
  google_fonts: 6.2.1
  json_annotation: 4.9.0
  local_auth: 2.3.0
  local_auth_android: 1.0.48
  local_auth_darwin: 1.4.3
  logging: 1.3.0
  provider: 6.1.4
  shared_preferences: 2.5.3

dev_dependencies:
  build_runner: 2.4.15
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.0.6
  go_router_builder: 2.8.2
  json_serializable: 6.9.4

flutter:
  uses-material-design: true
